// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYLpbCPlsqbsPwUveae7ycw-zFsg8TBb0',
    appId: '1:671906670250:web:19799ff1121989dcee52d3',
    messagingSenderId: '671906670250',
    projectId: 'miinventario-63bfa',
    authDomain: 'miinventario-63bfa.firebaseapp.com',
    storageBucket: 'miinventario-63bfa.firebasestorage.app',
    measurementId: 'G-B0Z3DDJ7GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUasOvWNzepWOjueiiXdjQJr5wkbU7BI',
    appId: '1:671906670250:android:b9f74c21d294c8fcee52d3',
    messagingSenderId: '671906670250',
    projectId: 'miinventario-63bfa',
    storageBucket: 'miinventario-63bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZ21JcjyOP7QFsJ6zI1Xcx0gUrw_sths',
    appId: '1:671906670250:ios:2762f6eb3ab25ec3ee52d3',
    messagingSenderId: '671906670250',
    projectId: 'miinventario-63bfa',
    storageBucket: 'miinventario-63bfa.firebasestorage.app',
    iosBundleId: 'com.example.miInventario',
  );
}
